spring:
  application:
    name: server
  datasource:
    password: ${DB_PASSWORD:postgres}
    username: ${DB_USER:postgres}
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:test}
  jpa:
    hibernate:
      ddl-auto: ${DB_DDL_AUTO:update}
    #    show-sql: false
    properties:
      hibernate:
        format_sql: true
